version: '3.8'

services:
    app:
        container_name: ${CONTAINER_NAME} # Nombre del contenedor: ${IMAGE_NAME}
        image: ${IMAGE_NAME}:${VERSION}  # Usar la variable IMAGE_NAME del archivo .env
#        build:
#            context: .
#            dockerfile: Dockerfile
        ports:
            - "${PORT}:8080"  # Usar la variable PORT del archivo .env
        volumes:
            - ${FILESYSTEM_PATH}:/input/videos  # Usar la variable FILESYSTEM_PATH del archivo .env
        environment:
            SPRING_PROFILES_ACTIVE: "${SPRING_PROFILE}"  # Usar la variable SPRING_PROFILE del archivo .env
        restart: always
