spring:
    application:
        name: ms-registrador

    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect


# CUSTOM
the-porndb:
    api:
        url: https://api.theporndb.net/scenes
        key: Bearer Giapd3HYbbCBdlEnkhYJ1igmeQVNzXnGs4yQINEQ8d872500
translation:
    api:
        url: https://api-inference.huggingface.co/models/Helsinki-NLP/opus-mt-en-es
        key: Bearer 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

const:
    config:
        nregistros: 5